### ISSUE TITLE
HTTPS: certificate problem re identity on only some pages

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1131] opened 2015-01-19 15:40 UTC
I am browsing the site via HTTPS and find that https://www.dreamwidth.org/latest and https://brainwane.dreamwidth.org/read give me a lock icon with a danger/warning sign on it in Chrome and Firefox. This is the *.dreamwidth.org cert. In Firefox I get "this website does not supply identity information". In Chrome I get "the identity of this website has been verified by RapidSSL CA but does not have public audit records." And both browsers complain about having some unencrypted content on the page (Connection Partially Encrypted), because of http://www.tumblr.com/favicon.ico and maybe others.

More details in Firefox:
* Owner: This website does not supply ownership information.
* Verified by: Not specified

Interestingly, if I am at https://brainwane.dreamwidth.org/profile , https://wiscon.dreamwidth.org/118455.html , or https://www.dreamwidth.org/ , I don't have these issues. The lock icon is green and the Firefox details say it's verified by "GeoTrust, Inc."

**Comment by afuna** [comment] 2015-01-20 05:36
Hmmm I'm guessing that that's all about mixed content, actually. Will
have to poke around more.


On Mon, Jan 19, 2015, at 11:40 PM, Sumana Harihareswara wrote:
> I am browsing the site via HTTPS and find that
> https://www.dreamwidth.org/latest and
> https://brainwane.dreamwidth.org/read give me a lock icon with a
> danger/warning sign on it in Chrome and Firefox. This is the
> *.dreamwidth.org cert. In Firefox I get "this website does not supply
> identity information". In Chrome I get "the identity of this website
> has been verified by RapidSSL CA but does not have public audit
> records." And both browsers complain about having some unencrypted
> content on the page (Connection Partially Encrypted), because of
> http://www.tumblr.com/favicon.ico and maybe others.


> More details in Firefox:


>  * Owner: This website does not supply ownership information.
>  * Verified by: Not specified Interestingly, if I am at
>    https://brainwane.dreamwidth.org/profile ,
>    https://wiscon.dreamwidth.org/118455.html , or
>    https://www.dreamwidth.org/ , I don't have these issues. The lock
>    icon is green and the Firefox details say it's verified by
>    "GeoTrust, Inc."


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1131

**Comment by afuna** [comment] 2015-01-25 07:09
Thanks for the report/links!

The mixed content stuff is definitely an issue; I'm filing bugs for each specific instance of a link that I can find (bunch of them are under the https everywhere milestones --  https://github.com/dreamwidth/dw-free/milestones/HTTPS%20Everywhere%20v1 https://github.com/dreamwidth/dw-free/milestones/HTTPS%20Everywhere%20v2)

Let's have this issue for the  the "Does not supply ownership information" / "Does not have public audit records" warnings. Note this appears to be a more general warning. On pages that don't have issues with mixed content -- such as brainwane.dreamwidth.org, you'll see the same warning message if you dig far enough (even when the HTTPS lock indicator looks good). e.g., Firefox -> lock indicator -> more information -> security

http://www.faqssys.info/what-exactly-does-it-mean-when-chrome-reports-a-certificate-does-not-have-public-audit-records/

has some info. 

Pinging @zorkian, @alierak as our ops people who handle the certificates and stuff ;)

**Comment by anall** [comment] 2015-02-14 23:02
"Does not have public audit records" is not the issue, as far as I can tell ( even Youtube and Github have that, if you check the detail )

I believe the danger/warning sign is because of the mixed content.

That is also the cause of "The site is using outdated security settings that may prevent future versions of Chrome from being able to safely access it."

**Comment by afuna** [comment] 2015-02-25 02:53
Agreed that the warning is because of the mixed content. I'm a little worried about "does not have public audit records", though, because from the sound of things (the article I linked and "...that may prevent future versions of Chrome...", it sounds like Chrome isn't / won't be happy without the audit records for much longer.

**Comment by anall** [comment] 2015-02-25 03:11
The may prevent future versions of chrome is also for the mixed content.
Googles own sites are missing audit records.

**Comment by afuna** [comment] 2015-02-25 03:18
Gotcha. in that case I'm closing this then since it doesn't seem like we'll end up doing anything here.

**Closed by afuna** 2015-02-25 03:18 UTC
Labels: status: untriaged
