### ISSUE TITLE
Membership option won't save in Account Settings

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2014] opened 2017-02-28 17:49 UTC
https://www.dreamwidth.org/support/see_request?id=35720
http://www.dreamwidth.org/support/see_request?id=35631

If you go to Account Settings to change the membership option of your community, it just won't save. It appears to, but if you refresh the page it hasn't and the setting doesn't seem to have been applied (the about section profile page didn't change either).

**Comment by rahaeli** [comment] 2017-03-30 05:47
Doing some research, it looks like the settings aren't properly being loaded in cgi-bin/LJ/Community.pm. I wondered if maybe the commit in https://github.com/dreamwidth/dw-free/commit/83faa4a1df8f645bdc6104507f51b32f830c957d#diff-8554e5015cba8b850e193383c7c05669 was to blame, but reverting Community.pm to an older version (without those changes) didn't fix the problem, alas. (That would've been too easy.)

**Comment by kareila** [comment] 2017-03-30 06:06
I don't think that change is live in production yet, so it is unlikely to be the cause!  😀

**Comment by rahaeli** [comment] 2017-03-30 06:26
Ha, yeah! I just always start my debugging with "see if the previous version displays the problem"...

(Next step, which I'm on right now, is liberally strewing print statements everywhere.)

**Comment by kareila** [comment] 2017-03-30 06:34
I confess that is still my most often used debugging method as well.  Especially when BML files are involved and line numbers are meaningless...

**Comment by zorkian** [comment] 2017-03-30 15:20
Debug prints are time honored and very effective.



I use them all the time everywhere.

**Comment by rahaeli** [comment] 2017-03-30 15:46
A little more investigation sez: I could reproduce the problem in my dev environment, but only for an old community that didn't already exist, and further investigation indicated that it was something fucked with my db, not whatever is causing the bug on prod: I couldn't reproduce it on a newly created comm. @zorkian did some database querying on prod as I updated settings for a community, and the first update (from a closed comm to an open one) made it to the db, while changing it from an open comm back to a closed one didn't. So, current theory: something is not being updated properly in memcache.

**Comment by azurelunatic** [comment] 2017-05-19 00:38
I duplicated (using angrybluedildo) in failing to change from a closed comm to an open one.

**Comment by rahaeli** [comment] 2017-05-20 05:16
Did not get far enough in troubleshooting this to feel like I can justify keeping it assigned...

**Comment by kaberett** [comment] 2017-06-05 14:33
https://www.dreamwidth.org/support/see_request?id=36851 and https://www.dreamwidth.org/support/see_request?id=36758 -- "I had this problem, figured it out by chance. For some reason, one has to tick the box 'Post to community'. I have no idea why it works but it does."

Might help with trouble-shooting? Might at least be worth updating the BBB? (Haven't replicated.)

**Comment by kareila** [comment] 2017-06-28 18:25
At least one user is reporting that this isn't just editing an existing community - the option either doesn't save or isn't loaded properly when editing a newly created community, either.

http://www.dreamwidth.org/support/see_request?id=36887

**Comment by ninetyd** [comment] 2017-07-31 22:40
Reports about this issue are somewhat piling up. Maybe it's time to make a post about it.

**Comment by ninetyd** [comment] 2017-08-06 15:09
https://www.dreamwidth.org/support/see_request?id=37225 Interesting bc they got it to save after it didn't work. This seems to confirm the inconsistency of the issue.

**Comment by alierak** [comment] 2017-08-29 00:26
So I think what's happening is that two settings are always saved in rapid sequence (membership and postlevel), and they live in the same row of the community table. The first time through, membership gets updated in the master db and set_comm_settings deletes the memcache entry, like you'd expect. The second time through, to set postlevel, we use get_comm_settings to retrieve the db row from a slave db that may or may not have replicated the previous change yet, then pair that value with the new postlevel and write the row back to the master db.

I think set_comm_settings should be two separate methods that each UPDATE one column of the community table, rather than reconstructing the whole row from potentially faulty data with REPLACE.

**Comment by alierak** [comment] 2017-08-29 00:30
Sometimes replication is fast enough that get_comm_settings will get the new membership value, sometimes it isn't. You don't need to try changing multiple settings, you can just resubmit the same thing several times in a row and it'll probably go through at some point.

**Comment by pauamma** [comment] 2018-01-08 21:33
Could/should this be fixed by always using a cluster master DB handle?

**Comment by zorkian** [comment] 2018-01-09 06:40
You could fix it that way, or having the fetch use get_definitive_reader IIRC. @alierak's suggestion of having it just do UPDATE instead of REPLACE is probably the best, though, since then you never head to read the row to do the modification.

If that's too hard given the codepath (I'm not looking at it right now) then just switching it to using the master handle is fine.

**Comment by alierak** [comment] 2018-02-12 01:05
claiming

**Closed** 2018-03-24 18:05 UTC
Labels: effort: (1) lower, from: support, is: bug, severity: (2) major, status: claimed
