### ISSUE TITLE
Success message error when deleting an account

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1755] opened 2016-04-17 17:34 UTC
This is what I get when I go to Account Settings / Status / Change then delete a community.

[Error: This event (uid=82545, extra=new=D&old=V) was not found in logs at /home/dw/production/cgi-bin/LJ/Event/SecurityAttributeChanged.pm line 47, line 13. @ sb-web14.dreamwidth.org]

Also got a similar message when deleting a second community :
The event (uid=243375, extra=new=D&old=V, logtime=1325277523) was found in log, but with wrong ip address (xxxx, but not xxxx) at /home/dw/production/cgi-bin/LJ/Event/SecurityAttributeChanged.pm line 53, line 10. @ sb-web11.dreamwidth.org]

The communities have been actually deleted, though.

**Comment by ninetyd** [comment] 2016-04-17 18:09
Also had a 'Sorry, there was a problem.' message when deleting a personal account. The account was deleted anyway.

**Comment by ninetyd** [comment] 2016-04-17 18:13
And it's just worked perfectly well for another account... Oh  and I see I'm supposed to get an email notif too. Didn't get it when I got the 'error' message.

**Comment by kareila** [comment] 2016-04-19 02:38
Yeah, this module defines the behavior for the ESN event that sends the notifications when the journal status changes.  A problem here won't stop the action from being taken on the journal, but if there's an issue with getting the relevant information back out of the userlog table, it spits out an error instead of failing gracefully.

This is old LJ code, and if we want to change it, we need to discuss what the new behavior should be.  Presumably the notification should still be sent, but with altered text if the requested information was not found or did not match what was expected.  The backend error messages should probably still be printed in the webserver logs, but not displayed to the user.

**Comment by kareila** [comment] 2017-04-28 21:38
I just realized this is a duplicate of #2016, which I diagnosed on my dreamhack.

**Closed by kareila** 2017-04-28 21:38 UTC
Labels: effort: (2) average, is: bug, severity: (1) minor
