### ISSUE TITLE
Rich text editor "Insert Image" function is broken

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1373] opened 2015-05-08 09:05 UTC
* Create a new post using the old (non-beta) page
* Have the Rich Text tab selected, and click the "Insert/Edit Image" button
- Note that in the resulting dialog box, there is a Cancel button but no OK or Submit button.

Observed in Firefox 37.0.2 and Chrome 42.0.2311.135 m, both on Win7/x64

**Comment by kareila** [comment] 2015-05-08 11:28
Duplicate of #1345.

(We should have a code push soon or else cherry pick this fix into production.)

**Closed by kareila** 2015-05-08 11:28 UTC
Labels: status: untriaged

**Comment by swaldman3** [comment] 2015-05-08 11:36
Huh. Sorry about the dupe. Why did 1345 not show up when I searched issues for "image"?

**Comment by kareila** [comment] 2015-05-08 11:39
It showed up for me just now. You may have inadvertently restricted your search to open issues only.

**Comment by swaldman3** [comment] 2015-05-08 11:43
Ah. Yes. I went to the dw-free repo, clicked "issues", and added my search to the search box. Seemed like a reasonable thing to do....
