### ISSUE TITLE
HTML cleaner should autoclose table tags

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1298] opened 2015-03-16 16:54 UTC
I don't know why exactly this changed behavior with the most recent push, but we have never automatically closed TD and TR tags when closing a table.  Look at t/cleaner-tables.t:
```
# VALID: table without closing tr/td tags
$orig_post = "<table><tr><td>Cell 1<td>Cell 2<tr><td>Cell 3<td>Cell 4</table>";
$clean->();
ok($orig_post eq $clean_post, "Table okay if td and tr tags aren't closed");
```
All of a sudden this is breaking pages where it wasn't before. We should implement the following rules in the cleaner:

- If a second TD is opened, close the first TD
- If a second TR is opened, close the first TR
- If a table is closed, close any open TDs and TRs

**Comment by afuna** [comment] 2015-03-16 23:44
Hmm can we confirm that this exact example breaks pages? I'm trying to reproduce as a first step to fixing, but I'm not seeing the breakage when I make a new entry with the contents of $orig_post.

**Comment by afuna** [comment] 2015-03-17 01:20
I think the problem code here is an open `<table>` tag that isn't closed.

Table without closing tr/td tags: that's optional and browsers should accept that, and do!

**Closed** 2015-03-17 04:13 UTC
Labels: status: claimed, status: untriaged

**Comment by kareila** [comment] 2015-03-17 04:55
Okay! I was just going off what I was seeing in comments on dw-maint last night, such as http://dw-maintenance.dreamwidth.org/67313.html?thread=2346225, where people were told they were missing their closing TD and TR tags.

**Comment by afuna** [comment] 2015-03-17 05:01
NP. I wasn’t meaning to correct, just trying to figure out what was wrong (I  
was mostly only able to see the corrected entries, not the original ones at  
that point) 



On Mon, Mar 16, 2015, at 09:55 PM, Jen wrote: 

> Okay! I was just going off what I was seeing in comments on dw-maint last  
> night, such as http://dw-maintenance.dreamwidth.org/67313.html? 
> thread=2346225, where people were told they were missing their closing TD  
> and TR tags.


> —
> Reply to this email directly or view it on GitHub[1].

>



Links: 


  1. https://github.com/dreamwidth/dw-free/issues/1298#issuecomment-82105242

**Comment by kareila** [comment] 2015-03-17 05:08
I think the change in behavior may have been due not to the cleaner changes, but to the change in doctype from XHTML to HTML5 :/

**Comment by afuna** [comment] 2015-03-17 05:16
I was worried that was the case, but no, we had actually done work around  
the HTML cleaner to make sure it worked for mismatched nesting of HTML tags,  
but that had the side effect of breaking non closed `table` tags. We’ve  
fixed that (I hope) and have pushed the fix live, so I’m waiting to hear if  
there are any more reports of breakage, or (better) reports of things being  
fixed. 



On Mon, Mar 16, 2015, at 10:08 PM, Jen wrote: 

> I think the change in behavior may have been due not to the cleaner  
> changes, but to the change in doctype from XHTML to HTML5 :/


> —
> Reply to this email directly or view it on GitHub[1].

>



Links: 


  1. https://github.com/dreamwidth/dw-free/issues/1298#issuecomment-82107840

**Comment by rahaeli** [comment] 2015-03-17 07:55
I have a copy of one of the problems I was looking at for people last night (that was manifesting the problem without the closing tags). LMK if you still want it.

**Comment by afuna** [comment] 2015-03-17 15:28
I think we've fixed it but toss it to me anyway so I can confirm!

**Comment by rahaeli** [comment] 2015-03-17 18:25
Cool, I'll email you since it's HTML-heavy.
