### ISSUE TITLE
investigate report of wandering tagnav element

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1303] opened 2015-03-17 05:36 UTC
http://dw-maintenance.dreamwidth.org/67313.html?thread=2378225#cmt2378225 includes screenshots

Browser appears to be Firefox on most recent Mac OS, journal style appears to be Five AM.

**Comment by afuna** [comment] 2015-03-26 21:30
I love the title of this bug :)

**Comment by rahaeli** [comment] 2015-03-26 22:15
It's on the Great American Roadtrip!

**Comment by woggy** [comment] 2015-06-30 13:33
Still borked. (Opera 30.0) Same behavior as before - arrows showing up at what's calculated to be the "first screen" of content even when the tags footer is offscreen.

**Comment by kareila** [comment] 2016-08-22 04:47
This is still happening: http://www.dreamwidth.org/support/see_request?id=33802

@afuna, I'm going to unassign this so someone else can pick it up, but feel free to reassign if you have time to look into it!

**Comment by nfagerlund** [comment] 2019-07-10 07:07
Oh hey, there's totally an issue for this already! 

I ran into this with foundationizing the site-style comment pages, then noticed it happens everywhere. (EXCEPT the old site-style comment pages. On those it's accurate.)

**Comment by nfagerlund** [comment] 2019-07-10 07:25
I think the problem is here https://github.com/dreamwidth/dw-free/blob/master/htdocs/js/journals/jquery.tag-nav.js#L37-L42

- The reason it works right on the old site-style pages is because the tagnav target is almost always visible on page load, since it's above the fold. On journal style pages, tags go below the entry, so on an entry that goes way below the fold, it stops at the bottom of the viewport. And then just sits there!
- I suspect the `collision: flipfit` bit. https://api.jqueryui.com/position/

    >  "fit": Shift the element away from the edge of the window.
    > "flipfit": First applies the flip logic, placing the element on whichever side allows more of the element to be visible. Then the fit logic is applied to ensure as much of the element is visible as possible.

We probably want plain old `'flip'` so it doesn't take the viewport into account, but idk what that'll break yet.

**Comment by nfagerlund** [comment] 2019-09-28 06:58
Hmmmmm I forgot to add the "fixes" keyword to that PR. Anyone with permissions wanna close this one?

**Closed** 2019-09-28 12:49 UTC
Labels: effort: (2) average, from: support, is: bug, severity: (1) minor, status: claimed
