### ISSUE TITLE
support reqs from D&P users can't be viewed

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2290] opened 2018-01-14 23:12 UTC
for instance, https://www.dreamwidth.org/support/see_request?id=37208 gets [Error: Database handle unavailable [user: grlmondaywrites; cluster: 0, errstr: ] at /home/dw/production/cgi-bin/DW/Media.pm line 229. @ va-web04] (and there's another one in Accounts, ditto)

**Comment by pauamma** [comment] 2018-01-15 01:16
Interesting. I'm not duplicating on my dreamhack, only on Dreamwidth. Has https://github.com/dreamwidth/dw-free/pull/2259 been pushed to production?

**Comment by pauamma** [comment] 2018-01-15 01:21
Looking at this more closely, it looks like a dupe of https://github.com/dreamwidth/dw-free/issues/2200, which has been fixed in dev.

**Closed** 2018-01-16 18:06 UTC
Labels: from: support, status: untriaged
