### ISSUE TITLE
non-member to see own content in no-longer member comm

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2242] opened 2017-11-28 21:01 UTC
@alierak  fixed the redirects, but now people can't see their content in communities without being members.  This is double plus ungood. 

I have no idea how to fix it.  Someone with dev knowledge, help.

**Comment by kareila** [comment] 2017-11-29 08:18
Duplicate of #1329 - this has never worked and we have wanted to fix it for a long time.

**Closed by kareila** 2017-11-29 08:18 UTC
Labels: status: untriaged
