### ISSUE TITLE
Elimate all non-free javascript

### ISSUE THREAD

**Issue by srukle** [dreamwidth/dw-free#1800] opened 2016-05-31 23:27 UTC
I attempted to use the sluggish Firefox app GNU LibreJS [1]. I don't use it any longer. But what I found was interesting, and I encourage DW administrators to give it a spin.

After using it, I decided to eliminate all non-free JavaScript code from sites I have made personally. For an example, I learned about the non-free JavaScript my site uses and eliminated it [2]. The site runs just as well as it did prior to running the non-free code.

When I used Dreamwidth, I noted that non-free JavaScript was detected. So I am asking a very broad and complicated question. Is there anyway Dreamwidth would support getting rid of its propriety code?

One thing I feel like I can be only critical about is the Google Analytics of the entire site. Could it be configured to be toggled by users who need it and disabled by default -- or at least toggled off for paid users?

[1] https://addons.mozilla.org/en-US/firefox/addon/librejs/?src=ss
[2] https://github.com/srukle/srukle.github.io/issues/1

**Comment by zorkian** [comment] 2016-05-31 23:39
We use GA for statistics about usage. I don't want to make that opt-out as a site-feature as you can already do that with various blocking tools like uBlock or Privacy Badger. I encourage and endorse people using such tools if they're concerned about the information that can be gathered from their browsing.

As for other JS, if there are particular things that we use that aren't free and are just providing site functionality, I'd be happy to replace them with free alternatives. I don't think I'm personally motivated to track them down and replace them, but I'd welcome and review any patches that did so. Given the choice between free software and not, I definitely would rather the former.

It'd be useful to have a list of non-free things that you've found. If it's only GA, then I will have to close this issue as WONTFIX, but if there are other examples then I think we can probably figure out if there are alternatives and use them.

**Comment by rahaeli** [comment] 2016-05-31 23:47
Ha, jinx, @zorkian -- I was already typing a response with much the same answer.

I'm going to agree with Mark, and in fact go a step further and close this issue, not because the answer is 'no' but because the answer is 'it's complicated' and any project to reduce or eliminate nonfree JS would be large, messy, and need careful specs and regression testing -- we've found that those kinds of bugs are really a bad fit for Github Issues, because they never end and it's impossible to keep track of and really hard to figure out what to do with them if the person who's working on the issue loses interest partway through.

dw-dev would be a better fit for the discussion, really -- if there are specific nonfree JS libraries you think can be replaced by an equivalent free JS library, you can post there and we can do the analysis to see if the replacement does do what we need it to do. (Then, once everybody agrees it's a good 1:1 equivalence, you can open individual issues for replacing each specific library.) Like Mark, I'm all for replacing nonfree stuff with free stuff! But generally speaking, in our dev history, we've only used nonfree alternatives when the person working on the project couldn't find an appropriate free library. Things certainly could have changed since then, and it's always worth a good thorough analysis, but one of our big priorities is not reinventing the wheel: if it's a choice between a nonfree library and rolling our own, we'll go with the nonfree library. (Rolling your own is how you get into messy situations where you're stuck maintaining a mass of nonstandard JS libraries that need constant bugfixes, browser fixes, and accessibility fixes.)

About Analytics: we use it to get information about how people are accessing the site (with what browsers, on what platforms, etc) in order to determine what our browser support policy should be, what browser bugs we need to target, what browser bugs we can safely ignore, etc. (For instance, "this bug only affects Browser X" is more important to fix when Browser X is 40% of our traffic vs 1% of our traffic.) We check it regularly, and it provides important information -- not having that information would be detrimental to the site. 

We already only add the Analytics code on site pages that don't have the potential to contain really personal stuff -- not on journals, not on locked/private entries, etc, etc. (People can individually enable it in their journals, but if they do, it's their own Analytics account, not DW's.) People who don't trust Analytics to only be doing what it says it's doing or don't want to contribute to those stats even anonymously can block the JS file (and we do recommend that in the Privacy Policy), with the caveat that it means their browser stats won't be counted in the aggregate anonymized data that we use to make decisions about the site.

**Closed by rahaeli** 2016-05-31 23:47 UTC
Labels: status: untriaged

**Comment by srukle** [comment] 2016-05-31 23:50
That's fair. GA stays.

Concerning other elements of the script, the problems seem to be in lofty high-level jargon, which may be a rabbit hole. Here're some examples of pages scanned with the LibreJS tool. Note "whitelist" indicates blocked script.

srukle journal [1]
dreamwidth homepage [2]
dreamwidth update [3]

[1] https://gist.github.com/srukle/5740bd8576f53ab8e488b263101c1f1c
[2] https://gist.github.com/srukle/08e31abccef4bc84760900588d67da6a
[3] https://gist.github.com/srukle/56c2fe8eb01fce2e0ce1b2ce75eef321

**Comment by srukle** [comment] 2016-05-31 23:54
That's understandable. I will put it on a chalkboard. If I feel inspired, I'll do some 1:1 analysis. I think it would be good experience. Thanks for your input.

**Comment by rahaeli** [comment] 2016-06-01 00:02
Hm, those reports seem to be calling out most of the JS on the page, which makes it hard to figure out what it's objecting to.

jQuery, which that extension seems to be calling out as nonfree, is MIT-licensed, which is OSI-approved. (And I *think* that all the jQuery plugins we use are likewise freely licensed, just based on their presence in dw-free -- I know @afuna was really careful about dw-free vs dw-nonfree for stuff like that when she was doing jQuery conversion.) Likewise, the DW-native JS is mostly dw-free stuff, which (like all of DW) is dual-licensed Artistic/GPL (also OSI-approved). So I'm not seeing anything in those reports that's specifically nonfree, although I might be missing something because the reports are hard for me to parse. 

The best place to start looking for JS that is actually nonfree (as opposed to JS that is free but that the extension is having trouble ID'ing as free) would probably be to go through dw-nonfree looking for it. Again, this is just a quick runthrough, but I *think* the only JS files in -nonfree are stuff that affects branding/service marks, which is nonfree so that other sites can't set up a site that looks exactly like DW. The more I poke at it, the more I think that + Analytics are the only actual nonfree JS we use.

Might be more worth digging through to see why the extension is identifying jQuery and the DW-native JS libraries as nonfree, and fixing that instead!

**Comment by srukle** [comment] 2016-06-01 00:05
Good thoughts. Thank you. It might be worth investigating to see if the problem is LibreJS and sending them some feedback.

**Comment by alierak** [comment] 2016-06-01 00:08
Its reporting of inline javascript seems particularly suspect. I don't think the tool has a way to detect that the inline javascript is being produced by open-source code from our dw-free repository...

**Comment by rahaeli** [comment] 2016-06-01 01:11
Yeah, I'm wondering if the tool expects some kind of inline license information in a comment or something that it's not getting?

(If that's the case, I don't think it's worth editing our source to include it -- we have the open source link in the footer which is human-readable if not machine-parseable, and adding a license comment in every JS file is a bit more overhead than I'd like to take on to appease a single tool.)

**Comment by srukle** [comment] 2016-06-01 01:32
(The tool is very unpopular, so such actions are justified.)

I might poke my nose in some communities to see what's up.
